//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs470project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCFDataEntities : DbContext
    {
        public CCFDataEntities()
            : base("name=CCFDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIM_Patient> DIM_Patient { get; set; }
        public virtual DbSet<DIM_Study> DIM_Study { get; set; }
        public virtual DbSet<FACT_Procedure> FACT_Procedure { get; set; }
        public virtual DbSet<ResearchProject> ResearchProjects { get; set; }
        public virtual DbSet<ResearchProjectAccession> ResearchProjectAccessions { get; set; }
        public virtual DbSet<ResearchProjectAccessionTag> ResearchProjectAccessionTags { get; set; }
        public virtual DbSet<ResearchProjectPatient> ResearchProjectPatients { get; set; }
        public virtual DbSet<ResearchProjectTag> ResearchProjectTags { get; set; }
        public virtual DbSet<ResearchProjectUser> ResearchProjectUsers { get; set; }
        public virtual DbSet<ResearchUser> ResearchUsers { get; set; }
        public virtual DbSet<GlobalAccession> GlobalAccessions { get; set; }
    }
}
