//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs470project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM_Study
    {
        public int SKey { get; set; }
        public string DepartmentCode { get; set; }
        public string ProcedureNumber { get; set; }
        public string LongDescription { get; set; }
    }
}
