//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs470project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT_Procedure
    {
        public int A_acc_itn { get; set; }
        public int A_pat_itn { get; set; }
        public string A_hosp { get; set; }
        public Nullable<System.DateTime> A_proc_dtime { get; set; }
        public string AI_dept { get; set; }
        public string RT_result { get; set; }
        public string RT_impression { get; set; }
        public Nullable<int> XAI_StudySKey { get; set; }
    }
}
