//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs470project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchProjectUser
    {
        public int Id { get; set; }
        public int ProjectID { get; set; }
        public int UserID { get; set; }
        public bool Admin { get; set; }
    
        public virtual ResearchProject ResearchProject { get; set; }
        public virtual ResearchUser ResearchUser { get; set; }
    }
}
