//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs470project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResearchProject()
        {
            this.ResearchProjectAccessions = new HashSet<ResearchProjectAccession>();
            this.ResearchProjectPatients = new HashSet<ResearchProjectPatient>();
            this.ResearchProjectTags = new HashSet<ResearchProjectTag>();
            this.ResearchProjectUsers = new HashSet<ResearchProjectUser>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string AccessionPrefix { get; set; }
        public string MRNPrefix { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchProjectAccession> ResearchProjectAccessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchProjectPatient> ResearchProjectPatients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchProjectTag> ResearchProjectTags { get; set; }
        public virtual ResearchUser ResearchUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchProjectUser> ResearchProjectUsers { get; set; }
    }
}
