//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs470project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchProjectPatient
    {
        public int ProjectID { get; set; }
        public long AlternateID { get; set; }
        public System.Guid AlternateGUID { get; set; }
        public string MRN { get; set; }
        public string MRNType { get; set; }
        public string AssigningAuthority { get; set; }
        public int pat_itn { get; set; }
        public string hosp { get; set; }
    
        public virtual ResearchProject ResearchProject { get; set; }
    }
}
